
namespace CafeShopApp_v1.PL
{
    partial class Generalite
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Generalite));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.mainPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.btnAnnuler = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAjouter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblTitle = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.txtTel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtAdresse = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnImg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtImg = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.checkLiv_Ste = new Bunifu.Framework.UI.BunifuCheckbox();
            this.chechPrix = new Bunifu.Framework.UI.BunifuCheckbox();
            this.lblprixJN = new System.Windows.Forms.Label();
            this.lblSteLiv = new System.Windows.Forms.Label();
            this.txtTimeDebut = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTimeFin = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.mainPanel.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // mainPanel
            // 
            this.mainPanel.BackgroundColor = System.Drawing.Color.White;
            this.mainPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainPanel.BackgroundImage")));
            this.mainPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.mainPanel.BorderColor = System.Drawing.Color.Transparent;
            this.mainPanel.BorderRadius = 15;
            this.mainPanel.BorderThickness = 0;
            this.mainPanel.Controls.Add(this.groupBox1);
            this.mainPanel.Controls.Add(this.chechPrix);
            this.mainPanel.Controls.Add(this.checkLiv_Ste);
            this.mainPanel.Controls.Add(this.btnImg);
            this.mainPanel.Controls.Add(this.txtImg);
            this.mainPanel.Controls.Add(this.label10);
            this.mainPanel.Controls.Add(this.txtAdresse);
            this.mainPanel.Controls.Add(this.label8);
            this.mainPanel.Controls.Add(this.txtTel);
            this.mainPanel.Controls.Add(this.label3);
            this.mainPanel.Controls.Add(this.txtEmail);
            this.mainPanel.Controls.Add(this.label2);
            this.mainPanel.Controls.Add(this.btnAnnuler);
            this.mainPanel.Controls.Add(this.btnAjouter);
            this.mainPanel.Controls.Add(this.txtName);
            this.mainPanel.Controls.Add(this.lblTitle);
            this.mainPanel.Controls.Add(this.lblSteLiv);
            this.mainPanel.Controls.Add(this.lblprixJN);
            this.mainPanel.Controls.Add(this.label1);
            this.mainPanel.Location = new System.Drawing.Point(8, 77);
            this.mainPanel.Margin = new System.Windows.Forms.Padding(0);
            this.mainPanel.Name = "mainPanel";
            this.mainPanel.ShowBorders = true;
            this.mainPanel.Size = new System.Drawing.Size(808, 558);
            this.mainPanel.TabIndex = 5;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 15;
            this.txtEmail.BorderThickness = 0;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(418, 276);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = true;
            this.txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Transparent;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties24;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtEmail.PlaceholderText = "Entrer l\'email de  Boutique";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(262, 40);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 14;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 10;
            this.txtEmail.TextMarginTop = 8;
            this.txtEmail.TextPlaceholder = "Entrer l\'email de  Boutique";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(419, 252);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(160, 21);
            this.label2.TabIndex = 13;
            this.label2.Text = "E-mail de  Boutique";
            // 
            // btnAnnuler
            // 
            this.btnAnnuler.AllowAnimations = true;
            this.btnAnnuler.AllowMouseEffects = true;
            this.btnAnnuler.AllowToggling = false;
            this.btnAnnuler.AnimationSpeed = 200;
            this.btnAnnuler.AutoGenerateColors = false;
            this.btnAnnuler.AutoRoundBorders = false;
            this.btnAnnuler.AutoSizeLeftIcon = true;
            this.btnAnnuler.AutoSizeRightIcon = true;
            this.btnAnnuler.BackColor = System.Drawing.Color.Transparent;
            this.btnAnnuler.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(95)))), ((int)(((byte)(63)))));
            this.btnAnnuler.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAnnuler.BackgroundImage")));
            this.btnAnnuler.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAnnuler.ButtonText = "Annuler";
            this.btnAnnuler.ButtonTextMarginLeft = 0;
            this.btnAnnuler.ColorContrastOnClick = 45;
            this.btnAnnuler.ColorContrastOnHover = 45;
            this.btnAnnuler.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAnnuler.CustomizableEdges = borderEdges2;
            this.btnAnnuler.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAnnuler.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAnnuler.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAnnuler.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAnnuler.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAnnuler.Font = new System.Drawing.Font("Montserrat", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAnnuler.ForeColor = System.Drawing.Color.White;
            this.btnAnnuler.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAnnuler.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAnnuler.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAnnuler.IconMarginLeft = 11;
            this.btnAnnuler.IconPadding = 10;
            this.btnAnnuler.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAnnuler.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAnnuler.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAnnuler.IconSize = 25;
            this.btnAnnuler.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAnnuler.IdleBorderRadius = 15;
            this.btnAnnuler.IdleBorderThickness = 1;
            this.btnAnnuler.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(95)))), ((int)(((byte)(63)))));
            this.btnAnnuler.IdleIconLeftImage = null;
            this.btnAnnuler.IdleIconRightImage = null;
            this.btnAnnuler.IndicateFocus = false;
            this.btnAnnuler.Location = new System.Drawing.Point(531, 488);
            this.btnAnnuler.Name = "btnAnnuler";
            this.btnAnnuler.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAnnuler.OnDisabledState.BorderRadius = 15;
            this.btnAnnuler.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAnnuler.OnDisabledState.BorderThickness = 1;
            this.btnAnnuler.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAnnuler.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAnnuler.OnDisabledState.IconLeftImage = null;
            this.btnAnnuler.OnDisabledState.IconRightImage = null;
            this.btnAnnuler.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAnnuler.onHoverState.BorderRadius = 15;
            this.btnAnnuler.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAnnuler.onHoverState.BorderThickness = 1;
            this.btnAnnuler.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAnnuler.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAnnuler.onHoverState.IconLeftImage = null;
            this.btnAnnuler.onHoverState.IconRightImage = null;
            this.btnAnnuler.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAnnuler.OnIdleState.BorderRadius = 15;
            this.btnAnnuler.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAnnuler.OnIdleState.BorderThickness = 1;
            this.btnAnnuler.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(95)))), ((int)(((byte)(63)))));
            this.btnAnnuler.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAnnuler.OnIdleState.IconLeftImage = null;
            this.btnAnnuler.OnIdleState.IconRightImage = null;
            this.btnAnnuler.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAnnuler.OnPressedState.BorderRadius = 15;
            this.btnAnnuler.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAnnuler.OnPressedState.BorderThickness = 1;
            this.btnAnnuler.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAnnuler.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAnnuler.OnPressedState.IconLeftImage = null;
            this.btnAnnuler.OnPressedState.IconRightImage = null;
            this.btnAnnuler.Size = new System.Drawing.Size(100, 40);
            this.btnAnnuler.TabIndex = 12;
            this.btnAnnuler.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAnnuler.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAnnuler.TextMarginLeft = 0;
            this.btnAnnuler.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAnnuler.UseDefaultRadiusAndThickness = true;
            this.btnAnnuler.Click += new System.EventHandler(this.btnAnnuler_Click);
            // 
            // btnAjouter
            // 
            this.btnAjouter.AllowAnimations = true;
            this.btnAjouter.AllowMouseEffects = true;
            this.btnAjouter.AllowToggling = false;
            this.btnAjouter.AnimationSpeed = 200;
            this.btnAjouter.AutoGenerateColors = false;
            this.btnAjouter.AutoRoundBorders = false;
            this.btnAjouter.AutoSizeLeftIcon = true;
            this.btnAjouter.AutoSizeRightIcon = true;
            this.btnAjouter.BackColor = System.Drawing.Color.Transparent;
            this.btnAjouter.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(195)))), ((int)(((byte)(137)))));
            this.btnAjouter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAjouter.BackgroundImage")));
            this.btnAjouter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAjouter.ButtonText = "Ajouter";
            this.btnAjouter.ButtonTextMarginLeft = 0;
            this.btnAjouter.ColorContrastOnClick = 45;
            this.btnAjouter.ColorContrastOnHover = 45;
            this.btnAjouter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAjouter.CustomizableEdges = borderEdges3;
            this.btnAjouter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAjouter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjouter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjouter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjouter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAjouter.Font = new System.Drawing.Font("Montserrat", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAjouter.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAjouter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjouter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAjouter.IconMarginLeft = 11;
            this.btnAjouter.IconPadding = 10;
            this.btnAjouter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAjouter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAjouter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAjouter.IconSize = 25;
            this.btnAjouter.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAjouter.IdleBorderRadius = 15;
            this.btnAjouter.IdleBorderThickness = 1;
            this.btnAjouter.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(195)))), ((int)(((byte)(137)))));
            this.btnAjouter.IdleIconLeftImage = null;
            this.btnAjouter.IdleIconRightImage = null;
            this.btnAjouter.IndicateFocus = false;
            this.btnAjouter.Location = new System.Drawing.Point(392, 488);
            this.btnAjouter.Name = "btnAjouter";
            this.btnAjouter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAjouter.OnDisabledState.BorderRadius = 15;
            this.btnAjouter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAjouter.OnDisabledState.BorderThickness = 1;
            this.btnAjouter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAjouter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAjouter.OnDisabledState.IconLeftImage = null;
            this.btnAjouter.OnDisabledState.IconRightImage = null;
            this.btnAjouter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAjouter.onHoverState.BorderRadius = 15;
            this.btnAjouter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAjouter.onHoverState.BorderThickness = 1;
            this.btnAjouter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAjouter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.onHoverState.IconLeftImage = null;
            this.btnAjouter.onHoverState.IconRightImage = null;
            this.btnAjouter.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAjouter.OnIdleState.BorderRadius = 15;
            this.btnAjouter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAjouter.OnIdleState.BorderThickness = 1;
            this.btnAjouter.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(195)))), ((int)(((byte)(137)))));
            this.btnAjouter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.OnIdleState.IconLeftImage = null;
            this.btnAjouter.OnIdleState.IconRightImage = null;
            this.btnAjouter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAjouter.OnPressedState.BorderRadius = 15;
            this.btnAjouter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAjouter.OnPressedState.BorderThickness = 1;
            this.btnAjouter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAjouter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAjouter.OnPressedState.IconLeftImage = null;
            this.btnAjouter.OnPressedState.IconRightImage = null;
            this.btnAjouter.Size = new System.Drawing.Size(100, 40);
            this.btnAjouter.TabIndex = 11;
            this.btnAjouter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAjouter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAjouter.TextMarginLeft = 0;
            this.btnAjouter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAjouter.UseDefaultRadiusAndThickness = true;
            this.btnAjouter.Click += new System.EventHandler(this.btnAjouter_Click);
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtName.BorderRadius = 15;
            this.txtName.BorderThickness = 0;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.White;
            this.txtName.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(55, 276);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = true;
            this.txtName.Name = "txtName";
            stateProperties25.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Transparent;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties28;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtName.PlaceholderText = "Entrer le nom de la Boutique";
            this.txtName.ReadOnly = false;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(262, 40);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 10;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 10;
            this.txtName.TextMarginTop = 8;
            this.txtName.TextPlaceholder = "Entrer le nom de la Boutique";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.Location = new System.Drawing.Point(20, 41);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(109, 21);
            this.lblTitle.TabIndex = 1;
            this.lblTitle.Text = "GENERALITE";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(51, 241);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(162, 21);
            this.label1.TabIndex = 9;
            this.label1.Text = "Nom de la Boutique";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(51, 333);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(203, 21);
            this.label3.TabIndex = 15;
            this.label3.Text = "Téléphone de la Boutique";
            // 
            // txtTel
            // 
            this.txtTel.AcceptsReturn = false;
            this.txtTel.AcceptsTab = false;
            this.txtTel.AnimationSpeed = 200;
            this.txtTel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTel.BackColor = System.Drawing.Color.Transparent;
            this.txtTel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTel.BackgroundImage")));
            this.txtTel.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtTel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTel.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtTel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTel.BorderRadius = 15;
            this.txtTel.BorderThickness = 0;
            this.txtTel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTel.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtTel.DefaultText = "";
            this.txtTel.FillColor = System.Drawing.Color.White;
            this.txtTel.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtTel.HideSelection = true;
            this.txtTel.IconLeft = null;
            this.txtTel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTel.IconPadding = 10;
            this.txtTel.IconRight = null;
            this.txtTel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTel.Lines = new string[0];
            this.txtTel.Location = new System.Drawing.Point(55, 357);
            this.txtTel.MaxLength = 32767;
            this.txtTel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTel.Modified = false;
            this.txtTel.Multiline = true;
            this.txtTel.Name = "txtTel";
            stateProperties17.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTel.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTel.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Transparent;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTel.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTel.OnIdleState = stateProperties20;
            this.txtTel.Padding = new System.Windows.Forms.Padding(3);
            this.txtTel.PasswordChar = '\0';
            this.txtTel.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtTel.PlaceholderText = "Entrer le  Téléphone de la Boutique";
            this.txtTel.ReadOnly = false;
            this.txtTel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTel.SelectedText = "";
            this.txtTel.SelectionLength = 0;
            this.txtTel.SelectionStart = 0;
            this.txtTel.ShortcutsEnabled = true;
            this.txtTel.Size = new System.Drawing.Size(262, 40);
            this.txtTel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTel.TabIndex = 16;
            this.txtTel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTel.TextMarginBottom = 0;
            this.txtTel.TextMarginLeft = 10;
            this.txtTel.TextMarginTop = 8;
            this.txtTel.TextPlaceholder = "Entrer le  Téléphone de la Boutique";
            this.txtTel.UseSystemPasswordChar = false;
            this.txtTel.WordWrap = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Transparent;
            this.label8.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(51, 420);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(189, 21);
            this.label8.TabIndex = 20;
            this.label8.Text = "Adresse de  la Boutique";
            // 
            // txtAdresse
            // 
            this.txtAdresse.AcceptsReturn = false;
            this.txtAdresse.AcceptsTab = false;
            this.txtAdresse.AnimationSpeed = 200;
            this.txtAdresse.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdresse.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdresse.BackColor = System.Drawing.Color.Transparent;
            this.txtAdresse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdresse.BackgroundImage")));
            this.txtAdresse.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtAdresse.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAdresse.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtAdresse.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAdresse.BorderRadius = 15;
            this.txtAdresse.BorderThickness = 0;
            this.txtAdresse.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdresse.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdresse.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtAdresse.DefaultText = "";
            this.txtAdresse.FillColor = System.Drawing.Color.White;
            this.txtAdresse.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtAdresse.HideSelection = true;
            this.txtAdresse.IconLeft = null;
            this.txtAdresse.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdresse.IconPadding = 10;
            this.txtAdresse.IconRight = null;
            this.txtAdresse.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdresse.Lines = new string[0];
            this.txtAdresse.Location = new System.Drawing.Point(55, 444);
            this.txtAdresse.MaxLength = 32767;
            this.txtAdresse.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdresse.Modified = false;
            this.txtAdresse.Multiline = true;
            this.txtAdresse.Name = "txtAdresse";
            stateProperties13.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdresse.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdresse.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Transparent;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdresse.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdresse.OnIdleState = stateProperties16;
            this.txtAdresse.Padding = new System.Windows.Forms.Padding(3);
            this.txtAdresse.PasswordChar = '\0';
            this.txtAdresse.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtAdresse.PlaceholderText = "Entrer l\'adresse de la Boutique";
            this.txtAdresse.ReadOnly = false;
            this.txtAdresse.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdresse.SelectedText = "";
            this.txtAdresse.SelectionLength = 0;
            this.txtAdresse.SelectionStart = 0;
            this.txtAdresse.ShortcutsEnabled = true;
            this.txtAdresse.Size = new System.Drawing.Size(262, 40);
            this.txtAdresse.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdresse.TabIndex = 21;
            this.txtAdresse.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdresse.TextMarginBottom = 0;
            this.txtAdresse.TextMarginLeft = 10;
            this.txtAdresse.TextMarginTop = 8;
            this.txtAdresse.TextPlaceholder = "Entrer l\'adresse de la Boutique";
            this.txtAdresse.UseSystemPasswordChar = false;
            this.txtAdresse.WordWrap = true;
            // 
            // btnImg
            // 
            this.btnImg.AllowAnimations = true;
            this.btnImg.AllowMouseEffects = true;
            this.btnImg.AllowToggling = false;
            this.btnImg.AnimationSpeed = 200;
            this.btnImg.AutoGenerateColors = false;
            this.btnImg.AutoRoundBorders = false;
            this.btnImg.AutoSizeLeftIcon = true;
            this.btnImg.AutoSizeRightIcon = true;
            this.btnImg.BackColor = System.Drawing.Color.Transparent;
            this.btnImg.BackColor1 = System.Drawing.Color.Black;
            this.btnImg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImg.BackgroundImage")));
            this.btnImg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImg.ButtonText = "Séléctioné";
            this.btnImg.ButtonTextMarginLeft = 0;
            this.btnImg.ColorContrastOnClick = 45;
            this.btnImg.ColorContrastOnHover = 45;
            this.btnImg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnImg.CustomizableEdges = borderEdges1;
            this.btnImg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnImg.Font = new System.Drawing.Font("Montserrat Light", 8.999999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnImg.ForeColor = System.Drawing.Color.White;
            this.btnImg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnImg.IconMarginLeft = 11;
            this.btnImg.IconPadding = 10;
            this.btnImg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnImg.IconSize = 25;
            this.btnImg.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnImg.IdleBorderRadius = 15;
            this.btnImg.IdleBorderThickness = 1;
            this.btnImg.IdleFillColor = System.Drawing.Color.Black;
            this.btnImg.IdleIconLeftImage = null;
            this.btnImg.IdleIconRightImage = null;
            this.btnImg.IndicateFocus = false;
            this.btnImg.Location = new System.Drawing.Point(423, 357);
            this.btnImg.Name = "btnImg";
            this.btnImg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImg.OnDisabledState.BorderRadius = 15;
            this.btnImg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImg.OnDisabledState.BorderThickness = 1;
            this.btnImg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImg.OnDisabledState.IconLeftImage = null;
            this.btnImg.OnDisabledState.IconRightImage = null;
            this.btnImg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnImg.onHoverState.BorderRadius = 15;
            this.btnImg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImg.onHoverState.BorderThickness = 1;
            this.btnImg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnImg.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnImg.onHoverState.IconLeftImage = null;
            this.btnImg.onHoverState.IconRightImage = null;
            this.btnImg.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnImg.OnIdleState.BorderRadius = 15;
            this.btnImg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImg.OnIdleState.BorderThickness = 1;
            this.btnImg.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnImg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnImg.OnIdleState.IconLeftImage = null;
            this.btnImg.OnIdleState.IconRightImage = null;
            this.btnImg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnImg.OnPressedState.BorderRadius = 15;
            this.btnImg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImg.OnPressedState.BorderThickness = 1;
            this.btnImg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnImg.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImg.OnPressedState.IconLeftImage = null;
            this.btnImg.OnPressedState.IconRightImage = null;
            this.btnImg.Size = new System.Drawing.Size(118, 40);
            this.btnImg.TabIndex = 66;
            this.btnImg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImg.TextMarginLeft = 0;
            this.btnImg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnImg.UseDefaultRadiusAndThickness = true;
            this.btnImg.Click += new System.EventHandler(this.btnImg_Click);
            // 
            // txtImg
            // 
            this.txtImg.AcceptsReturn = false;
            this.txtImg.AcceptsTab = false;
            this.txtImg.AnimationSpeed = 200;
            this.txtImg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtImg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtImg.BackColor = System.Drawing.Color.Transparent;
            this.txtImg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtImg.BackgroundImage")));
            this.txtImg.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtImg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtImg.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtImg.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtImg.BorderRadius = 15;
            this.txtImg.BorderThickness = 0;
            this.txtImg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtImg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtImg.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtImg.DefaultText = "";
            this.txtImg.FillColor = System.Drawing.Color.White;
            this.txtImg.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtImg.HideSelection = true;
            this.txtImg.IconLeft = null;
            this.txtImg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtImg.IconPadding = 10;
            this.txtImg.IconRight = null;
            this.txtImg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtImg.Lines = new string[0];
            this.txtImg.Location = new System.Drawing.Point(517, 357);
            this.txtImg.MaxLength = 32767;
            this.txtImg.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtImg.Modified = false;
            this.txtImg.Multiline = true;
            this.txtImg.Name = "txtImg";
            stateProperties9.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtImg.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtImg.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtImg.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtImg.OnIdleState = stateProperties12;
            this.txtImg.Padding = new System.Windows.Forms.Padding(3);
            this.txtImg.PasswordChar = '\0';
            this.txtImg.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtImg.PlaceholderText = "0 Fichier choisi";
            this.txtImg.ReadOnly = true;
            this.txtImg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtImg.SelectedText = "";
            this.txtImg.SelectionLength = 0;
            this.txtImg.SelectionStart = 0;
            this.txtImg.ShortcutsEnabled = true;
            this.txtImg.Size = new System.Drawing.Size(163, 40);
            this.txtImg.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtImg.TabIndex = 65;
            this.txtImg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtImg.TextMarginBottom = 0;
            this.txtImg.TextMarginLeft = 30;
            this.txtImg.TextMarginTop = 9;
            this.txtImg.TextPlaceholder = "0 Fichier choisi";
            this.txtImg.UseSystemPasswordChar = false;
            this.txtImg.WordWrap = true;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.Transparent;
            this.label10.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(419, 333);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(167, 21);
            this.label10.TabIndex = 64;
            this.label10.Text = "Logo  de la Boutique";
            // 
            // checkLiv_Ste
            // 
            this.checkLiv_Ste.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.checkLiv_Ste.ChechedOffColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(135)))), ((int)(((byte)(140)))));
            this.checkLiv_Ste.Checked = true;
            this.checkLiv_Ste.CheckedOnColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.checkLiv_Ste.ForeColor = System.Drawing.Color.White;
            this.checkLiv_Ste.Location = new System.Drawing.Point(55, 203);
            this.checkLiv_Ste.Name = "checkLiv_Ste";
            this.checkLiv_Ste.Size = new System.Drawing.Size(20, 20);
            this.checkLiv_Ste.TabIndex = 67;
            // 
            // chechPrix
            // 
            this.chechPrix.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.chechPrix.ChechedOffColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(135)))), ((int)(((byte)(140)))));
            this.chechPrix.Checked = true;
            this.chechPrix.CheckedOnColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.chechPrix.ForeColor = System.Drawing.Color.White;
            this.chechPrix.Location = new System.Drawing.Point(57, 89);
            this.chechPrix.Name = "chechPrix";
            this.chechPrix.Size = new System.Drawing.Size(20, 20);
            this.chechPrix.TabIndex = 68;
            this.chechPrix.OnChange += new System.EventHandler(this.chechPrix_OnChange);
            // 
            // lblprixJN
            // 
            this.lblprixJN.AutoSize = true;
            this.lblprixJN.BackColor = System.Drawing.Color.Transparent;
            this.lblprixJN.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblprixJN.Location = new System.Drawing.Point(53, 88);
            this.lblprixJN.Name = "lblprixJN";
            this.lblprixJN.Size = new System.Drawing.Size(259, 21);
            this.lblprixJN.TabIndex = 9;
            this.lblprixJN.Text = "        Activer le mode prix variable";
            this.lblprixJN.Click += new System.EventHandler(this.lblprixJN_Click);
            // 
            // lblSteLiv
            // 
            this.lblSteLiv.AutoSize = true;
            this.lblSteLiv.BackColor = System.Drawing.Color.Transparent;
            this.lblSteLiv.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSteLiv.Location = new System.Drawing.Point(51, 202);
            this.lblSteLiv.Name = "lblSteLiv";
            this.lblSteLiv.Size = new System.Drawing.Size(314, 21);
            this.lblSteLiv.TabIndex = 9;
            this.lblSteLiv.Text = "        Exploitation de sociétés de livraison";
            this.lblSteLiv.Click += new System.EventHandler(this.lblSteLiv_Click);
            // 
            // txtTimeDebut
            // 
            this.txtTimeDebut.AcceptsReturn = false;
            this.txtTimeDebut.AcceptsTab = false;
            this.txtTimeDebut.AnimationSpeed = 200;
            this.txtTimeDebut.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTimeDebut.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTimeDebut.BackColor = System.Drawing.Color.Transparent;
            this.txtTimeDebut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTimeDebut.BackgroundImage")));
            this.txtTimeDebut.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtTimeDebut.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTimeDebut.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtTimeDebut.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTimeDebut.BorderRadius = 15;
            this.txtTimeDebut.BorderThickness = 0;
            this.txtTimeDebut.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTimeDebut.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeDebut.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtTimeDebut.DefaultText = "";
            this.txtTimeDebut.Enabled = false;
            this.txtTimeDebut.FillColor = System.Drawing.Color.White;
            this.txtTimeDebut.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtTimeDebut.HideSelection = true;
            this.txtTimeDebut.IconLeft = null;
            this.txtTimeDebut.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeDebut.IconPadding = 10;
            this.txtTimeDebut.IconRight = null;
            this.txtTimeDebut.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeDebut.Lines = new string[0];
            this.txtTimeDebut.Location = new System.Drawing.Point(51, 32);
            this.txtTimeDebut.MaxLength = 32767;
            this.txtTimeDebut.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTimeDebut.Modified = false;
            this.txtTimeDebut.Multiline = true;
            this.txtTimeDebut.Name = "txtTimeDebut";
            stateProperties1.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeDebut.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTimeDebut.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeDebut.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeDebut.OnIdleState = stateProperties4;
            this.txtTimeDebut.Padding = new System.Windows.Forms.Padding(3);
            this.txtTimeDebut.PasswordChar = '\0';
            this.txtTimeDebut.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtTimeDebut.PlaceholderText = "Time Début Jour";
            this.txtTimeDebut.ReadOnly = true;
            this.txtTimeDebut.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTimeDebut.SelectedText = "";
            this.txtTimeDebut.SelectionLength = 0;
            this.txtTimeDebut.SelectionStart = 0;
            this.txtTimeDebut.ShortcutsEnabled = true;
            this.txtTimeDebut.Size = new System.Drawing.Size(142, 40);
            this.txtTimeDebut.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTimeDebut.TabIndex = 14;
            this.txtTimeDebut.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTimeDebut.TextMarginBottom = 0;
            this.txtTimeDebut.TextMarginLeft = 10;
            this.txtTimeDebut.TextMarginTop = 8;
            this.txtTimeDebut.TextPlaceholder = "Time Début Jour";
            this.txtTimeDebut.UseSystemPasswordChar = false;
            this.txtTimeDebut.WordWrap = true;
            this.txtTimeDebut.Validating += new System.ComponentModel.CancelEventHandler(this.txtTimeDebut_Validating);
            // 
            // txtTimeFin
            // 
            this.txtTimeFin.AcceptsReturn = false;
            this.txtTimeFin.AcceptsTab = false;
            this.txtTimeFin.AnimationSpeed = 200;
            this.txtTimeFin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTimeFin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTimeFin.BackColor = System.Drawing.Color.Transparent;
            this.txtTimeFin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTimeFin.BackgroundImage")));
            this.txtTimeFin.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtTimeFin.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTimeFin.BorderColorHover = System.Drawing.Color.Transparent;
            this.txtTimeFin.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTimeFin.BorderRadius = 15;
            this.txtTimeFin.BorderThickness = 0;
            this.txtTimeFin.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTimeFin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeFin.DefaultFont = new System.Drawing.Font("Montserrat", 9F);
            this.txtTimeFin.DefaultText = "";
            this.txtTimeFin.Enabled = false;
            this.txtTimeFin.FillColor = System.Drawing.Color.White;
            this.txtTimeFin.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.txtTimeFin.HideSelection = true;
            this.txtTimeFin.IconLeft = null;
            this.txtTimeFin.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeFin.IconPadding = 10;
            this.txtTimeFin.IconRight = null;
            this.txtTimeFin.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTimeFin.Lines = new string[0];
            this.txtTimeFin.Location = new System.Drawing.Point(222, 32);
            this.txtTimeFin.MaxLength = 32767;
            this.txtTimeFin.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTimeFin.Modified = false;
            this.txtTimeFin.Multiline = true;
            this.txtTimeFin.Name = "txtTimeFin";
            stateProperties5.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeFin.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTimeFin.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeFin.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTimeFin.OnIdleState = stateProperties8;
            this.txtTimeFin.Padding = new System.Windows.Forms.Padding(3);
            this.txtTimeFin.PasswordChar = '\0';
            this.txtTimeFin.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtTimeFin.PlaceholderText = "Time Fin Jour";
            this.txtTimeFin.ReadOnly = true;
            this.txtTimeFin.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTimeFin.SelectedText = "";
            this.txtTimeFin.SelectionLength = 0;
            this.txtTimeFin.SelectionStart = 0;
            this.txtTimeFin.ShortcutsEnabled = true;
            this.txtTimeFin.Size = new System.Drawing.Size(142, 40);
            this.txtTimeFin.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTimeFin.TabIndex = 14;
            this.txtTimeFin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTimeFin.TextMarginBottom = 0;
            this.txtTimeFin.TextMarginLeft = 10;
            this.txtTimeFin.TextMarginTop = 8;
            this.txtTimeFin.TextPlaceholder = "Time Fin Jour";
            this.txtTimeFin.UseSystemPasswordChar = false;
            this.txtTimeFin.WordWrap = true;
            this.txtTimeFin.Validating += new System.ComponentModel.CancelEventHandler(this.txtTimeFin_Validating);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(196, 41);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(23, 21);
            this.label5.TabIndex = 69;
            this.label5.Text = " à";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Montserrat SemiBold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(19, 40);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(31, 21);
            this.label6.TabIndex = 70;
            this.label6.Text = "De";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.txtTimeDebut);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.txtTimeFin);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Font = new System.Drawing.Font("Montserrat Light", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(93, 112);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(372, 84);
            this.groupBox1.TabIndex = 71;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Time Début Jour de";
            // 
            // Generalite
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.mainPanel);
            this.Name = "Generalite";
            this.Size = new System.Drawing.Size(824, 713);
            this.mainPanel.ResumeLayout(false);
            this.mainPanel.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel mainPanel;
        public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAnnuler;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAjouter;
        public Bunifu.UI.WinForms.BunifuTextBox txtName;
        public System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label label1;
        public Bunifu.UI.WinForms.BunifuTextBox txtAdresse;
        private System.Windows.Forms.Label label8;
        public Bunifu.UI.WinForms.BunifuTextBox txtTel;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnImg;
        public Bunifu.UI.WinForms.BunifuTextBox txtImg;
        private System.Windows.Forms.Label label10;
        private Bunifu.Framework.UI.BunifuCheckbox chechPrix;
        private Bunifu.Framework.UI.BunifuCheckbox checkLiv_Ste;
        private System.Windows.Forms.Label lblSteLiv;
        private System.Windows.Forms.Label lblprixJN;
        public Bunifu.UI.WinForms.BunifuTextBox txtTimeFin;
        public Bunifu.UI.WinForms.BunifuTextBox txtTimeDebut;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.GroupBox groupBox1;
    }
}
