//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class achat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public achat()
        {
            this.achat_details = new HashSet<achat_details>();
        }
    
        public int id_achat { get; set; }
        public Nullable<System.DateTime> date_achat { get; set; }
        public Nullable<int> fournisseur { get; set; }
        public Nullable<int> responsable_achat { get; set; }
        public Nullable<decimal> montant_total { get; set; }
        public Nullable<decimal> montant_rest { get; set; }
        public Nullable<bool> iscredit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<achat_details> achat_details { get; set; }
        public virtual fournisseur fournisseur1 { get; set; }
        public virtual user user { get; set; }
    }
}
