//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Cfe_shop_dbEntities : DbContext
    {
        public Cfe_shop_dbEntities()
            : base("name=Cfe_shop_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<achat_details> achat_details { get; set; }
        public virtual DbSet<achat> achats { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<charge> charges { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<commande_details> commande_details { get; set; }
        public virtual DbSet<commande_details_annuler> commande_details_annuler { get; set; }
        public virtual DbSet<commande> commandes { get; set; }
        public virtual DbSet<espace> espaces { get; set; }
        public virtual DbSet<fournisseur> fournisseurs { get; set; }
        public virtual DbSet<info> infos { get; set; }
        public virtual DbSet<livraison_produit> livraison_produit { get; set; }
        public virtual DbSet<mode_reg> mode_reg { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<produit> produits { get; set; }
        public virtual DbSet<reglement> reglements { get; set; }
        public virtual DbSet<ste_livraisons> ste_livraisons { get; set; }
        public virtual DbSet<tb_tables> tb_tables { get; set; }
        public virtual DbSet<type_charge> type_charge { get; set; }
        public virtual DbSet<unite> unites { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_privileges> users_privileges { get; set; }
    
        public virtual int allowed_user(Nullable<int> id_user, string place)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var placeParameter = place != null ?
                new ObjectParameter("place", place) :
                new ObjectParameter("place", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("allowed_user", id_userParameter, placeParameter);
        }
    
        public virtual ObjectResult<get_all_achat_details_Result> get_all_achat_details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_achat_details_Result>("get_all_achat_details");
        }
    
        public virtual ObjectResult<get_all_achats_Result> get_all_achats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_achats_Result>("get_all_achats");
        }
    
        public virtual ObjectResult<get_all_attend_cmd_Result> get_all_attend_cmd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_attend_cmd_Result>("get_all_attend_cmd");
        }
    
        public virtual ObjectResult<get_all_categories_Result> get_all_categories(Nullable<bool> a_chate)
        {
            var a_chateParameter = a_chate.HasValue ?
                new ObjectParameter("a_chate", a_chate) :
                new ObjectParameter("a_chate", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_categories_Result>("get_all_categories", a_chateParameter);
        }
    
        public virtual ObjectResult<get_all_charges_Result> get_all_charges()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_charges_Result>("get_all_charges");
        }
    
        public virtual ObjectResult<get_all_clients_Result> get_all_clients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_clients_Result>("get_all_clients");
        }
    
        public virtual ObjectResult<get_all_cmd_Result> get_all_cmd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_cmd_Result>("get_all_cmd");
        }
    
        public virtual ObjectResult<get_all_commande_details_Result> get_all_commande_details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_commande_details_Result>("get_all_commande_details");
        }
    
        public virtual ObjectResult<get_all_espaces_Result> get_all_espaces()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_espaces_Result>("get_all_espaces");
        }
    
        public virtual ObjectResult<get_all_fournisseurs_Result> get_all_fournisseurs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_fournisseurs_Result>("get_all_fournisseurs");
        }
    
        public virtual ObjectResult<get_all_infos_Result> get_all_infos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_infos_Result>("get_all_infos");
        }
    
        public virtual ObjectResult<get_all_livraison_produit_Result> get_all_livraison_produit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_livraison_produit_Result>("get_all_livraison_produit");
        }
    
        public virtual ObjectResult<get_all_mode_reg_Result> get_all_mode_reg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_mode_reg_Result>("get_all_mode_reg");
        }
    
        public virtual ObjectResult<get_all_notes_Result> get_all_notes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_notes_Result>("get_all_notes");
        }
    
        public virtual ObjectResult<get_all_notes_by_categorie_Result> get_all_notes_by_categorie(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_notes_by_categorie_Result>("get_all_notes_by_categorie", idParameter);
        }
    
        public virtual ObjectResult<get_all_produits_achat_Result> get_all_produits_achat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_achat_Result>("get_all_produits_achat");
        }
    
        public virtual ObjectResult<get_all_produits_achat_by_categorie_Result> get_all_produits_achat_by_categorie(Nullable<int> id_cat)
        {
            var id_catParameter = id_cat.HasValue ?
                new ObjectParameter("id_cat", id_cat) :
                new ObjectParameter("id_cat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_achat_by_categorie_Result>("get_all_produits_achat_by_categorie", id_catParameter);
        }
    
        public virtual ObjectResult<get_all_produits_Achat_by_id_Result> get_all_produits_Achat_by_id(Nullable<int> id_prod)
        {
            var id_prodParameter = id_prod.HasValue ?
                new ObjectParameter("id_prod", id_prod) :
                new ObjectParameter("id_prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_Achat_by_id_Result>("get_all_produits_Achat_by_id", id_prodParameter);
        }
    
        public virtual ObjectResult<get_all_produits_vente_Result> get_all_produits_vente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_vente_Result>("get_all_produits_vente");
        }
    
        public virtual ObjectResult<get_all_produits_vente_by_categorie_Result> get_all_produits_vente_by_categorie(Nullable<int> id_cat)
        {
            var id_catParameter = id_cat.HasValue ?
                new ObjectParameter("id_cat", id_cat) :
                new ObjectParameter("id_cat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_vente_by_categorie_Result>("get_all_produits_vente_by_categorie", id_catParameter);
        }
    
        public virtual ObjectResult<get_all_produits_vente_by_id_Result> get_all_produits_vente_by_id(Nullable<int> id_prod)
        {
            var id_prodParameter = id_prod.HasValue ?
                new ObjectParameter("id_prod", id_prod) :
                new ObjectParameter("id_prod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_produits_vente_by_id_Result>("get_all_produits_vente_by_id", id_prodParameter);
        }
    
        public virtual ObjectResult<get_all_reglements_Result> get_all_reglements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_reglements_Result>("get_all_reglements");
        }
    
        public virtual ObjectResult<get_all_ste_livraisons_Result> get_all_ste_livraisons()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_ste_livraisons_Result>("get_all_ste_livraisons");
        }
    
        public virtual ObjectResult<get_all_tables_Result> get_all_tables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_tables_Result>("get_all_tables");
        }
    
        public virtual ObjectResult<get_all_type_charges_Result> get_all_type_charges()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_type_charges_Result>("get_all_type_charges");
        }
    
        public virtual ObjectResult<get_all_Unite_Result> get_all_Unite(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_Unite_Result>("get_all_Unite", strSearchParameter);
        }
    
        public virtual ObjectResult<get_all_unites_Result> get_all_unites()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_unites_Result>("get_all_unites");
        }
    
        public virtual ObjectResult<get_all_users_Result> get_all_users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_all_users_Result>("get_all_users");
        }
    
        public virtual ObjectResult<get_auth_user_Result> get_auth_user(string mot_passe)
        {
            var mot_passeParameter = mot_passe != null ?
                new ObjectParameter("mot_passe", mot_passe) :
                new ObjectParameter("mot_passe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_auth_user_Result>("get_auth_user", mot_passeParameter);
        }
    
        public virtual ObjectResult<get_categories_by_str_search_Result> get_categories_by_str_search(string strSearch, Nullable<bool> a_chat)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            var a_chatParameter = a_chat.HasValue ?
                new ObjectParameter("a_chat", a_chat) :
                new ObjectParameter("a_chat", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_categories_by_str_search_Result>("get_categories_by_str_search", strSearchParameter, a_chatParameter);
        }
    
        public virtual ObjectResult<get_charges_by_str_search_Result> get_charges_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_charges_by_str_search_Result>("get_charges_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_clients_by_str_search_Result> get_clients_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_clients_by_str_search_Result>("get_clients_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_cmd_by_str_search_Result> get_cmd_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_cmd_by_str_search_Result>("get_cmd_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_credit_client_by_str_search_Result> get_credit_client_by_str_search(string strSearch, Nullable<int> idclient)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            var idclientParameter = idclient.HasValue ?
                new ObjectParameter("idclient", idclient) :
                new ObjectParameter("idclient", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_credit_client_by_str_search_Result>("get_credit_client_by_str_search", strSearchParameter, idclientParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> get_data_daily_rapport(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("get_data_daily_rapport", dateParameter);
        }
    
        public virtual ObjectResult<get_data_tecket_Result> get_data_tecket(Nullable<int> id_cmd)
        {
            var id_cmdParameter = id_cmd.HasValue ?
                new ObjectParameter("id_cmd", id_cmd) :
                new ObjectParameter("id_cmd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_data_tecket_Result>("get_data_tecket", id_cmdParameter);
        }
    
        public virtual ObjectResult<get_espaces_by_str_search_Result> get_espaces_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_espaces_by_str_search_Result>("get_espaces_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_fournisseurs_by_str_search_Result> get_fournisseurs_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_fournisseurs_by_str_search_Result>("get_fournisseurs_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> get_montant_total_all_cmd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("get_montant_total_all_cmd");
        }
    
        public virtual ObjectResult<Nullable<decimal>> get_montant_total_cmd_visiteur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("get_montant_total_cmd_visiteur");
        }
    
        public virtual ObjectResult<get_produit_achat_by_str_search_Result> get_produit_achat_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_produit_achat_by_str_search_Result>("get_produit_achat_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_produit_vente_by_str_search_Result> get_produit_vente_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_produit_vente_by_str_search_Result>("get_produit_vente_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_reg_client_by_str_search_Result> get_reg_client_by_str_search(string strSearch, Nullable<int> idclient)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            var idclientParameter = idclient.HasValue ?
                new ObjectParameter("idclient", idclient) :
                new ObjectParameter("idclient", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_reg_client_by_str_search_Result>("get_reg_client_by_str_search", strSearchParameter, idclientParameter);
        }
    
        public virtual ObjectResult<get_steLiv_by_str_search_Result> get_steLiv_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_steLiv_by_str_search_Result>("get_steLiv_by_str_search", strSearchParameter);
        }
    
        public virtual ObjectResult<get_users_by_str_search_Result> get_users_by_str_search(string strSearch)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("strSearch", strSearch) :
                new ObjectParameter("strSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_users_by_str_search_Result>("get_users_by_str_search", strSearchParameter);
        }
    }
}
