//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande_details
    {
        public int cmd { get; set; }
        public int produit { get; set; }
        public Nullable<int> qte_prod { get; set; }
        public string note { get; set; }
        public Nullable<decimal> prix_vente { get; set; }
    
        public virtual produit produit1 { get; set; }
        public virtual commande commande { get; set; }
    }
}
