//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commande()
        {
            this.commande_details = new HashSet<commande_details>();
            this.commande_details_annuler = new HashSet<commande_details_annuler>();
        }
    
        public int id_cmd { get; set; }
        public string type_cmd { get; set; }
        public Nullable<System.DateTime> date_cmd { get; set; }
        public string t_able { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> responsable { get; set; }
        public Nullable<bool> enattend { get; set; }
        public string statu { get; set; }
        public Nullable<decimal> montant_total { get; set; }
        public Nullable<decimal> montant_rest { get; set; }
        public Nullable<bool> isready { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> modifiedd_at { get; set; }
        public Nullable<int> delivery_company { get; set; }
    
        public virtual client client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande_details> commande_details { get; set; }
        public virtual ste_livraisons ste_livraisons { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande_details_annuler> commande_details_annuler { get; set; }
    }
}
