//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int id_info { get; set; }
        public string name_boutique { get; set; }
        public byte[] logo { get; set; }
        public string adresse { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public bool Prix_J_N { get; set; }
        public bool Liveraison { get; set; }
        public System.TimeSpan Time_Debut_J { get; set; }
        public System.TimeSpan Time_F_J { get; set; }
    }
}
