//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class livraison_produit
    {
        public int liv { get; set; }
        public int produit { get; set; }
        public Nullable<decimal> prix_jour { get; set; }
        public Nullable<decimal> prix_nuit { get; set; }
    
        public virtual produit produit1 { get; set; }
        public virtual ste_livraisons ste_livraisons { get; set; }
    }
}
