//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int id_note { get; set; }
        public Nullable<int> cat { get; set; }
        public string note1 { get; set; }
    
        public virtual category category { get; set; }
    }
}
