//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.achat_details = new HashSet<achat_details>();
            this.commande_details = new HashSet<commande_details>();
            this.livraison_produit = new HashSet<livraison_produit>();
            this.commande_details_annuler = new HashSet<commande_details_annuler>();
        }
    
        public int id_produit { get; set; }
        public string name_produit { get; set; }
        public Nullable<bool> consom_directe { get; set; }
        public byte[] image_produit { get; set; }
        public string lieu_préparation { get; set; }
        public Nullable<decimal> prix_jour { get; set; }
        public Nullable<decimal> prix_nuit { get; set; }
        public Nullable<int> categorie_Vent { get; set; }
        public Nullable<int> categorie_Achat { get; set; }
        public Nullable<int> unite_prod { get; set; }
        public Nullable<int> qte_stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<achat_details> achat_details { get; set; }
        public virtual category category { get; set; }
        public virtual category category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande_details> commande_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livraison_produit> livraison_produit { get; set; }
        public virtual unite unite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commande_details_annuler> commande_details_annuler { get; set; }
    }
}
