//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reglement
    {
        public int id_reg { get; set; }
        public Nullable<int> fornisseur { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<System.DateTime> date_reg { get; set; }
        public Nullable<decimal> montant { get; set; }
        public string mode_payment { get; set; }
    
        public virtual client client1 { get; set; }
        public virtual fournisseur fournisseur { get; set; }
    }
}
