//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tables
    {
        public int id_table { get; set; }
        public string name_table { get; set; }
        public string statu { get; set; }
        public Nullable<int> espace { get; set; }
    
        public virtual espace espace1 { get; set; }
    }
}
