//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeShopApp_v1.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_privileges
    {
        public int idprivileges { get; set; }
        public Nullable<int> id_Utilisateur { get; set; }
        public Nullable<bool> controle_Panel { get; set; }
        public Nullable<bool> c_aisse { get; set; }
        public Nullable<bool> p_roduits { get; set; }
        public Nullable<bool> s_tock { get; set; }
        public Nullable<bool> c_lients { get; set; }
        public Nullable<bool> f_ournisseurs { get; set; }
        public Nullable<bool> a_chats { get; set; }
        public Nullable<bool> c_harges { get; set; }
        public Nullable<bool> c_ommandes { get; set; }
        public Nullable<bool> s_te_liv { get; set; }
        public Nullable<bool> e_spaces { get; set; }
        public Nullable<bool> u_nites { get; set; }
        public Nullable<bool> c_ategories { get; set; }
        public Nullable<bool> u_tilisateur { get; set; }
        public Nullable<bool> g_eneralite { get; set; }
    }
}
